server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: tp_final
      port: 28017
      host: mongodb2

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Series Microservice
